import { useMemo, useState } from "react";
import { Link, Route, Switch, useLocation, useRoute } from "wouter";
import {
  ArrowRight, Bell, Bookmark, BookOpen, ChevronRight, Compass, Heart, Home,
  Library, LogIn, Menu, MessageCircle, MoreHorizontal, PenLine, Search,
  Settings, Share2, Sparkles, Star, UserRound, Users, X
} from "lucide-react";
import { Toaster, toast } from "sonner";
import { ThemeProvider } from "./contexts/ThemeContext";
import "./index.css";

const hero = "/manus-storage/bookish-hero_cda01606.png";
const mark = "/manus-storage/bookish-logo-mark_a648670d.png";

const books = [
  { id: "midnight-library", title: "The Midnight Library", author: "Matt Haig", genre: "Fiction", rating: 4.6, ratings: "12.4k", cover: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=85", blurb: "Between life and death there is a library. And within that library, the shelves go on forever." },
  { id: "kindred", title: "Kindred", author: "Octavia E. Butler", genre: "Speculative", rating: 4.8, ratings: "8.7k", cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=85", blurb: "A powerful, time-bending story about memory, survival, and the ties that bind us." },
  { id: "piranesi", title: "Piranesi", author: "Susanna Clarke", genre: "Literary fantasy", rating: 4.7, ratings: "6.1k", cover: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=85", blurb: "A house of infinite rooms, a tide that rises and falls, and a mystery written in the margins." },
  { id: "assembly", title: "Assembly", author: "Natasha Brown", genre: "Contemporary", rating: 4.3, ratings: "3.2k", cover: "https://images.unsplash.com/photo-1526243741027-444d633d7365?auto=format&fit=crop&w=600&q=85", blurb: "A lucid, razor-sharp novel about class, ambition, and the stories we inherit." },
  { id: "sea", title: "The Sea, The Sea", author: "Iris Murdoch", genre: "Classic", rating: 4.5, ratings: "4.9k", cover: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=85", blurb: "An unreliable narrator, a retreat by the sea, and a past that refuses to stay buried." },
];
const recs = [
  { id: "r1", user: "Mina Patel", handle: "@minareads", avatar: "MP", book: books[2], note: "Read this when you want to feel wonderfully lost. The house is a puzzle, but the real mystery is the tenderness underneath it.", likes: 248, comments: 31, time: "2h ago" },
  { id: "r2", user: "Jon Bell", handle: "@jonbell", avatar: "JB", book: books[1], note: "The kind of book that changes shape the longer you sit with it. I underlined nearly every page.", likes: 184, comments: 19, time: "5h ago" },
];

function Rating({ value, large = false }: { value: number; large?: boolean }) {
  return <span className={`rating ${large ? "rating-large" : ""}`}><Star size={large ? 17 : 14} fill="currentColor" /> {value.toFixed(1)}</span>;
}
function Cover({ book, className = "" }: { book: typeof books[number]; className?: string }) {
  return <img className={`book-cover ${className}`} src={book.cover} alt={`Cover of ${book.title}`} />;
}
function Logo() { return <Link href="/" className="logo"><img src={mark} alt="" /><span>bookish</span></Link>; }
function TopBar({ onMenu }: { onMenu: () => void }) {
  const [, navigate] = useLocation();
  return <header className="topbar"><div className="topbar-inner"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={onMenu}><Menu size={20}/></button><Logo /><div className="global-search" onClick={() => navigate("/search")}><Search size={17}/><span>Search books, authors, or genres</span><kbd>⌘ K</kbd></div><div className="top-actions"><button className="icon-button" aria-label="Notifications" onClick={() => toast("You’re all caught up") }><Bell size={19}/><i /></button><Link href="/users/alex" className="avatar avatar-small">AR</Link></div></div></header>;
}
const nav = [{ href: "/feed", label: "Home", icon: Home }, { href: "/explore", label: "Explore", icon: Compass }, { href: "/search", label: "Search", icon: Search }, { href: "/recommend", label: "Recommend", icon: PenLine }, { href: "/my-library", label: "My library", icon: Library }];
function Sidebar({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [loc] = useLocation();
  return <aside className={`sidebar ${open ? "sidebar-open" : ""}`}><div className="sidebar-brand"><Logo /><button className="icon-button close-mobile" onClick={onClose}><X size={18}/></button></div><nav className="nav-list">{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={`nav-link ${loc === href ? "active" : ""}`} onClick={onClose}><Icon size={18}/><span>{label}</span>{label === "Search" && <kbd>/</kbd>}</Link>)}</nav><div className="nav-divider" /><p className="nav-eyebrow">Your reading</p><Link href="/activity" className="nav-link"><MessageCircle size={18}/><span>Activity</span></Link><Link href="/followers" className="nav-link"><Users size={18}/><span>Following</span></Link><div className="sidebar-spacer" /><div className="sidebar-profile"><div className="avatar">AR</div><div><strong>Alex Rivera</strong><span>@alexreads</span></div><MoreHorizontal size={18} className="muted" /></div><Link href="/settings" className="nav-link settings-link"><Settings size={18}/><span>Settings</span></Link></aside>;
}
function AppShell({ children }: { children: React.ReactNode }) { const [open, setOpen] = useState(false); return <div className="app-frame"><TopBar onMenu={() => setOpen(true)} /><Sidebar open={open} onClose={() => setOpen(false)} /><main className="page-shell">{children}</main><nav className="bottom-nav">{nav.slice(0, 5).map(({ href, label, icon: Icon }) => <Link href={href} key={href}><Icon size={18}/><span>{label === "My library" ? "Library" : label}</span></Link>)}</nav></div>; }
function SectionHeading({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: string }) { return <div className="section-heading"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2></div>{action && <Link href="/explore" className="text-link">{action}<ArrowRight size={15}/></Link>}</div>; }
function BookCard({ book, compact = false }: { book: typeof books[number]; compact?: boolean }) { return <Link href={`/books/${book.id}`} className={`book-card ${compact ? "compact" : ""}`}><div className="cover-wrap"><Cover book={book}/><button className="save-button" aria-label={`Save ${book.title}`} onClick={(e) => { e.preventDefault(); toast(`${book.title} saved to your library`); }}><Bookmark size={16}/></button></div><div className="book-meta"><h3>{book.title}</h3><p>{book.author}</p><div><Rating value={book.rating}/><span className="rating-count">{book.ratings} ratings</span></div></div></Link>; }
function RecommendationCard({ rec }: { rec: typeof recs[number] }) { const [liked, setLiked] = useState(false); return <article className="rec-card"><div className="rec-header"><div className="avatar avatar-clay">{rec.avatar}</div><div><strong>{rec.user}</strong><span>{rec.handle} · {rec.time}</span></div><button className="icon-button subtle"><MoreHorizontal size={18}/></button></div><p className="rec-note">“{rec.note}”</p><div className="rec-book"><Cover book={rec.book}/><div><p className="eyebrow">Recommended book</p><h3>{rec.book.title}</h3><p>{rec.book.author}</p><Rating value={rec.book.rating}/></div><ChevronRight size={18} className="rec-arrow" /></div><div className="rec-actions"><button className={liked ? "liked" : ""} onClick={() => setLiked(!liked)}><Heart size={17} fill={liked ? "currentColor" : "none"}/> {rec.likes + (liked ? 1 : 0)}</button><button><MessageCircle size={17}/> {rec.comments}</button><button><Share2 size={17}/> Share</button></div></article>; }
function Feed() { return <AppShell><div className="content-grid"><section className="main-column"><div className="page-intro"><div><p className="eyebrow">Tuesday, August 20</p><h1>Your reading room</h1><p className="intro-copy">A quiet place to find your next good book.</p></div><Link href="/recommend" className="button button-primary"><PenLine size={16}/> Recommend a book</Link></div><div className="feed-tabs"><button className="tab active">For you</button><button className="tab">Following</button><button className="tab">Popular</button></div><div className="feed-stack">{recs.map(r => <RecommendationCard key={r.id} rec={r}/>)}</div></section><aside className="right-rail"><div className="rail-card"><SectionHeading eyebrow="A little nudge" title="Continue reading"/><div className="continue-book"><Cover book={books[0]}/><div><h3>{books[0].title}</h3><p>Chapter 7 of 18</p><div className="progress"><span style={{width: "42%"}} /></div><small>42% complete</small></div></div><button className="button button-ink full" onClick={() => toast("Opening your reading list")}>Open reading list <ArrowRight size={15}/></button></div><div className="rail-card"><SectionHeading eyebrow="Because you liked Piranesi" title="You might enjoy"/><div className="mini-books">{books.slice(3, 5).map(b => <BookCard key={b.id} book={b} compact/>)}</div></div></aside></div></AppShell>; }
function Landing() { return <div className="landing"><header className="landing-nav"><Logo/><div><Link href="/login" className="nav-plain">Log in</Link><Link href="/register" className="button button-primary small">Join Bookish <ArrowRight size={15}/></Link></div></header><section className="landing-hero"><div className="hero-copy"><p className="eyebrow">A social reading room</p><h1>Find your next favorite in the <em>margins.</em></h1><p>Discover books worth reading through people worth following. Keep the good conversations going.</p><div className="hero-actions"><Link href="/explore" className="button button-primary">Explore books <ArrowRight size={16}/></Link><Link href="/register" className="button button-ghost">Join the community</Link></div><div className="hero-proof"><div className="avatar-stack"><span className="avatar">MP</span><span className="avatar avatar-clay">JB</span><span className="avatar avatar-sage">SK</span></div><span>Join 24,000 curious readers</span></div></div><div className="hero-art"><img src={hero} alt="Books and coffee in a warm reading room"/><div className="hero-note"><Sparkles size={16}/><span>Books worth talking about</span></div></div></section><section className="how-section"><div className="section-lead"><p className="eyebrow">How it works</p><h2>Read more like<br/><em>yourself.</em></h2></div><div className="how-steps">{[["01","Discover","Follow the threads that lead from one great book to another."],["02","Rate","Keep a record of what moved you — and what didn’t."],["03","Recommend","Put a good book in someone else’s path."],["04","Connect","Find readers who see the world a little like you do."]].map(([n,t,d]) => <div className="how-step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section><section className="landing-books"><SectionHeading eyebrow="On the nightstand" title="Trending right now" action="Explore all"/><div className="book-shelf">{books.slice(0,4).map(b => <BookCard key={b.id} book={b}/>)}</div></section><section className="landing-cta"><div><p className="eyebrow">Your next chapter starts here</p><h2>Bring the book<br/><em>with you.</em></h2></div><Link href="/register" className="button button-ochre">Make a reading list <ArrowRight size={16}/></Link></section><footer className="landing-footer"><Logo/><span>Made for people who still dog-ear pages.</span></footer></div>; }
function Explore() { return <AppShell><div className="page-intro"><div><p className="eyebrow">The shelves are open</p><h1>Explore books</h1><p className="intro-copy">A few places to begin when you’re not sure what you’re looking for.</p></div></div><div className="explore-feature"><div><p className="eyebrow">Editor’s shelf</p><h2>Books that leave<br/><em>a little light on.</em></h2><p>A considered collection of new perspectives, old friends, and stories that refuse to sit quietly.</p><Link href="/books/piranesi" className="button button-ochre">Browse the shelf <ArrowRight size={15}/></Link></div><Cover book={books[2]}/></div><SectionHeading eyebrow="Most saved this week" title="The good stuff"/><div className="book-grid">{books.map(b => <BookCard key={b.id} book={b}/>)}</div></AppShell>; }
function SearchPage() { const [q, setQ] = useState(""); const results = useMemo(() => books.filter(b => `${b.title} ${b.author} ${b.genre}`.toLowerCase().includes(q.toLowerCase())), [q]); return <AppShell><div className="search-page"><p className="eyebrow">Search the shelves</p><h1>What are you<br/><em>in the mood for?</em></h1><div className="big-search"><Search size={22}/><input autoFocus value={q} onChange={e => setQ(e.target.value)} placeholder="Title, author, or genre"/><kbd>⌘ K</kbd></div><div className="search-meta"><span>{q ? `${results.length} results for “${q}”` : "Popular searches"}</span><div className="chip-row">{["Literary fiction","Warm reads","Short books","Octavia Butler"].map(x => <button key={x} className="chip" onClick={() => setQ(x)}>{x}</button>)}</div></div><div className="book-grid search-results">{results.map(b => <BookCard key={b.id} book={b}/>)}</div></div></AppShell>; }
function BookDetails() { const [, params] = useRoute("/books/:bookId"); const book = books.find(b => b.id === params?.bookId) || books[2]; const [saved, setSaved] = useState(false); return <AppShell><Link href="/explore" className="back-link">← Back to explore</Link><div className="book-detail"><div className="detail-cover"><Cover book={book}/><button className="save-float" onClick={() => {setSaved(!saved); toast(saved ? "Removed from library" : "Saved to library");}}><Bookmark size={17} fill={saved ? "currentColor" : "none"}/>{saved ? "Saved" : "Save to library"}</button></div><div className="detail-copy"><p className="eyebrow">{book.genre}</p><h1>{book.title}</h1><p className="detail-author">by <u>{book.author}</u></p><div className="detail-rating"><Rating value={book.rating} large/><span>{book.ratings} reader ratings</span></div><p className="detail-blurb">{book.blurb} A book for the curious, the restless, and anyone who has ever wondered what might have happened on a different page.</p><div className="detail-actions"><button className="button button-primary" onClick={() => toast("Rating saved — thank you")}>Rate this book <Star size={16}/></button><button className="button button-outline" onClick={() => toast("Recommendation composer opened")}>Recommend it <Share2 size={16}/></button></div><div className="detail-note"><span className="avatar avatar-sage">SK</span><p><strong>Samira says:</strong> “The kind of story that stays in the room after you’ve closed the cover.”</p></div></div></div><div className="detail-lower"><SectionHeading eyebrow="From the community" title="Readers are talking"/><div className="feed-stack"><RecommendationCard rec={recs[0]}/></div></div></AppShell>; }
function Auth({ register = false }: { register?: boolean }) { const [, navTo] = useLocation(); return <div className="auth-page"><div className="auth-aside"><Logo/><div><p className="eyebrow">A social reading room</p><h1>{register ? "Make a little room for more good books." : "Welcome back to the good part."}</h1><p>{register ? "Keep the stories, people, and ideas that stay with you in one place." : "Your shelves, your people, and a few recommendations waiting in the wings."}</p></div><span className="auth-quote">“A reader lives a thousand lives before he dies.”</span></div><div className="auth-form-wrap"><Link href="/" className="back-link">← Back to Bookish</Link><form className="auth-form" onSubmit={e => {e.preventDefault(); navTo("/feed"); toast("Welcome to your reading room");}}><p className="eyebrow">{register ? "Create your account" : "Sign in"}</p><h2>{register ? "Start your reading life here." : "Good to see you again."}</h2>{register && <><label>Display name<input placeholder="Alex Rivera" required /></label><label>Username<input placeholder="@alexreads" required /></label></>}<label>Email address<input type="email" placeholder="you@example.com" required /></label><label>Password<div className="password-field"><input type="password" placeholder="••••••••" required/><button type="button" onClick={() => toast("Password visibility toggle ready for API wiring")} aria-label="Toggle password visibility">Show</button></div></label>{!register && <Link href="/login" className="forgot">Forgot password?</Link>}<button className="button button-primary full" type="submit">{register ? "Create my account" : "Continue"} <ArrowRight size={16}/></button><p className="auth-switch">{register ? "Already have an account?" : "New to Bookish?"} <Link href={register ? "/login" : "/register"}>{register ? "Sign in" : "Join the community"}</Link></p></form></div></div>; }
function SimplePage({ title, kicker }: { title: string; kicker: string }) { return <AppShell><div className="page-intro"><div><p className="eyebrow">{kicker}</p><h1>{title}</h1><p className="intro-copy">This part of your reading room is ready for your next conversation.</p></div></div><div className="empty-panel"><BookOpen size={28}/><h2>Make some room for good things.</h2><p>Connect your API when you’re ready. The frontend service layer is set up to make that handoff straightforward.</p><Link href="/explore" className="button button-primary">Find a book <ArrowRight size={15}/></Link></div></AppShell>; }
function App() { return <><Toaster position="bottom-right"/><Switch><Route path="/" component={Landing}/><Route path="/login"><Auth/></Route><Route path="/register"><Auth register/></Route><Route path="/search" component={SearchPage}/><Route path="/books/:bookId" component={BookDetails}/><Route path="/explore" component={Explore}/><Route path="/feed" component={Feed}/><Route path="/recommend"><SimplePage title="Recommend a book" kicker="Put a good book in someone else’s path"/></Route><Route path="/my-library"><SimplePage title="My library" kicker="Your shelves"/></Route><Route path="/activity"><SimplePage title="Activity" kicker="The people you follow"/></Route><Route path="/followers"><SimplePage title="Following" kicker="Your reading circle"/></Route><Route path="/settings"><SimplePage title="Settings" kicker="Make Bookish yours"/></Route><Route path="/users/:username"><SimplePage title="Alex Rivera" kicker="@alexreads"/></Route><Route path="/recommendations/:id"><SimplePage title="A recommendation worth keeping" kicker="From the community"/></Route><Route><SimplePage title="Page not found" kicker="404"/></Route></Switch></>; }
export default App;
